Homework1
SerhiiDykyi/nodejs pull request #2
Opened 2020-09-06 14:53 UTC by SerhiiDykyi

completed homework 1 for node

2020-09-07 10:41 UTC, odykyi commented on contacts.js
> +  fs.writeFile(contactsPath, resultAsJSON);
await

2020-09-07 10:41 UTC, odykyi commented on contacts.js
> +  fs.writeFile(contactsPath, contactAsJSON);
await

2020-09-07 10:41 UTC, odykyi requested changes
comments

2020-09-08 06:44 UTC, SerhiiDykyi commented
I added await

2020-09-08 08:07 UTC, odykyi approved these changes

2020-09-08 08:07 UTC, merged