05 images
SerhiiDykyi/nodejs pull request #6
Opened 2020-10-05 18:26 UTC by SerhiiDykyi

completed home work 05-images without additional task

2020-10-06 10:20 UTC, odykyi commented on api/auth/auth.controller.js
> +    image.png().toFile(`public/images/${body.email}.png`);
move `public/images/${body.email}.png` to config 

```export const yourFunction = (id) => `public/images/${id}.png````

2020-10-06 10:21 UTC, odykyi commented on api/auth/auth.controller.js
> +      avatarURL: `http:3000/images/${body.email}.png`,
move protocol, host, port , File Fomat to config

2020-10-06 10:21 UTC, odykyi commented on api/auth/auth.controller.js
> +    const avatarURL = `http://localhost:3000/images/${file.filename}`;
move to config

2020-10-06 10:22 UTC, odykyi commented on index.js
>      app.use(cors({ origin: 'http://localhost:3000' }));
move url to config

2020-10-06 10:22 UTC, odykyi commented on index.js
> +      express.static(path.resolve(__dirname, 'public/images')),
move path to config

2020-10-06 10:22 UTC, odykyi commented on middlewares/fileUploader.middleware.js
> +      cb(null, 'public/images');
move path to config

2020-10-06 10:23 UTC, odykyi commented on services/avatar.services.js
> +  partsLocation: path.join(__dirname, '../img'),
move partsLocation to config

2020-10-06 10:23 UTC, odykyi requested changes
comments

2020-10-08 14:40 UTC, SerhiiDykyi commented
fix problems

2020-10-12 17:59 UTC, odykyi commented on api/auth/auth.controller.js
> +    madeAvatar(newUser._id);
await

2020-10-12 18:11 UTC, SerhiiDykyi commented
del images, add await madeAvatar

2020-10-12 18:39 UTC, odykyi approved these changes

2020-10-12 18:40 UTC, merged